config_type: "evaluation"
evaluation_name: "full_benchmark_eval"
episode_paths:
  - "configs/task_configs/banana_into_bowl.yaml"
  - "configs/task_configs/block_into_basket.yaml"
  - "configs/task_configs/baseball_into_bucket.yaml"
  - "configs/task_configs/bread_and_apple_into_bowl.yaml"
  - "configs/task_configs/bread_from_box.yaml"
  - "configs/task_configs/drawer_close.yaml"
  - "configs/task_configs/cloth_fold.yaml"
  - "configs/task_configs/banana_under_cloth.yaml"