config_type: "policy"
policy_name: pi0
policy_checkpoint: "gs://openpi-assets/checkpoints/pi0_droid"
remote_host: localhost
remote_port: 8000
open_loop_horizon: 8
action_space: "joint_velocity"
gripper_space: "position"