config_type: "policy"
policy_name: pi05
policy_checkpoint: "gs://openpi-assets/checkpoints/pi05_droid"
default_remote_host: localhost
default_remote_port: 8000
open_loop_horizon: 8
action_space: "joint_velocity"
gripper_space: "position"